### ISSUE TITLE
Remove note on conformance publishing process

### ISSUE THREAD

**Issue by pmjordan** [oasis-tcs/tosca-specs#141]
This comment item was contained in csd06 section 18 and moved here as part of https://github.com/oasis-tcs/tosca-specs/issues/61

> (Note: The [OASIS TC
> Process](https://www.oasis-open.org/policies-guidelines/tc-process-2017-05-26/#wpComponentsConfClause)
> requires that a specification approved by the TC at the Committee
> Specification Public Review Draft, Committee Specification or OASIS
> Standard level must include a separate section, listing a set of
> numbered conformance clauses, to which any implementation of the
> specification must adhere in order to claim conformance to the
> specification (or any optional portion thereof). This is done by
> listing the conformance clauses here.  For the definition of
> "conformance clause," see [OASIS Defined
> Terms](https://www.oasis-open.org/policies-guidelines/oasis-defined-terms-2018-05-22/#dConformanceClause).

> See "Guidelines to Writing Conformance Clauses":
> https://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html.

> Remove this note before submitting for publication.)

**Comment by lauwers** [comment]
Fixed in https://github.com/oasis-tcs/tosca-specs/pull/186
