### ISSUE TITLE
Deprecated key name valid_source_types

### ISSUE THREAD

**Issue by r0light** [oasis-tcs/tosca-specs#167]
On page 88 or section 8.2 of TOSCA 2.0 csd06, the deprecated key name `valid_source_types` is still used and should probably be replaced with `valid_source_node_types` and `valid_relationship_types` respectively

![page88](https://github.com/user-attachments/assets/ee730caa-e00e-4a79-b938-b66262f3f023)

**Comment by lauwers** [comment]
Fixed in https://github.com/oasis-tcs/tosca-specs/pull/186
