### ISSUE TITLE
Deal with "Root"

### ISSUE THREAD

**Issue by koppor** [oasis-tcs/tosca-specs#184]
Spec has some `derived_from: Root` in the text:

![image](https://github.com/user-attachments/assets/4ef8f439-56ef-4c92-813b-4e8481f0426b)

![image](https://github.com/user-attachments/assets/e6ad0f35-1114-42c6-910d-71ad0b93a9a6)

However, there is no text saying where this `Root` comes from.

Can we remove all `derived_from: ...Root` lines?

---

The TOSCA intro file has text about it : https://github.com/oasis-tcs/tosca-specs/blob/working/tosca_intro/tosca-intro-v2.0.md#node-lifecycle-definition

The TOSCA 1.3 spec had it - example: https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_TYPE_ARTIFACTS_ROOT

**Comment by koppor** [comment]
The TOSCA 1.3 spec had it - example: https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#DEFN_TYPE_ARTIFACTS_ROOT

**Comment by lauwers** [comment]
Fixed in https://github.com/oasis-tcs/tosca-specs/pull/186
