### ISSUE TITLE
Document conventions

### ISSUE THREAD

**Issue by lauwers** [oasis-tcs/tosca-specs#58]
The Document Conventions section is currently empty. Are there any conventions that need to be documented? Have we made sure the document adheres to these conventions?

**Comment by tliron** [comment]
Things to address:

* italics (?) when introducing specific, named terms
* monospace for computer-read strings: keynames, reserved values, etc.
* We do "\<insert value here\>" in snippets, which is invalid YAML, so find another convention
* capitalization of section names
